// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SistemaPredio.Database;

#nullable disable

namespace SistemaPredio.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20250902181618_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("SistemaPredio.Model.Admin", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UsuarioId")
                        .IsUnique();

                    b.ToTable("Admin");
                });

            modelBuilder.Entity("SistemaPredio.Model.Aluguel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DataVencimento")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("Preco")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("codigoApartamento")
                        .IsRequired()
                        .HasColumnType("nvarchar(5)");

                    b.Property<string>("cpfMorador")
                        .HasMaxLength(11)
                        .HasColumnType("nvarchar(11)");

                    b.HasKey("Id");

                    b.HasIndex("codigoApartamento");

                    b.HasIndex("cpfMorador");

                    b.ToTable("Aluguel");
                });

            modelBuilder.Entity("SistemaPredio.Model.Apartamento", b =>
                {
                    b.Property<string>("Codigo")
                        .HasMaxLength(5)
                        .HasColumnType("nvarchar(5)");

                    b.Property<int>("Andar")
                        .HasColumnType("int");

                    b.Property<string>("cpfMorador")
                        .HasColumnType("nvarchar(11)");

                    b.HasKey("Codigo");

                    b.HasIndex("cpfMorador");

                    b.ToTable("Apartamento");
                });

            modelBuilder.Entity("SistemaPredio.Model.Morador", b =>
                {
                    b.Property<string>("CPF")
                        .HasMaxLength(11)
                        .HasColumnType("nvarchar(11)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Telefone")
                        .IsRequired()
                        .HasMaxLength(11)
                        .HasColumnType("nvarchar(11)");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("int");

                    b.HasKey("CPF");

                    b.HasIndex("UsuarioId")
                        .IsUnique();

                    b.ToTable("Morador");
                });

            modelBuilder.Entity("SistemaPredio.Model.Usuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(10)
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CPF")
                        .IsRequired()
                        .HasMaxLength(11)
                        .HasColumnType("nvarchar(11)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("Role")
                        .HasColumnType("int");

                    b.Property<string>("Senha")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("CPF")
                        .IsUnique();

                    b.ToTable("Usuario");
                });

            modelBuilder.Entity("SistemaPredio.Model.Admin", b =>
                {
                    b.HasOne("SistemaPredio.Model.Usuario", "Usuario")
                        .WithOne()
                        .HasForeignKey("SistemaPredio.Model.Admin", "UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("SistemaPredio.Model.Aluguel", b =>
                {
                    b.HasOne("SistemaPredio.Model.Apartamento", "Apartamento")
                        .WithMany("Alugueis")
                        .HasForeignKey("codigoApartamento")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SistemaPredio.Model.Morador", "Morador")
                        .WithMany("Alugueis")
                        .HasForeignKey("cpfMorador")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("Apartamento");

                    b.Navigation("Morador");
                });

            modelBuilder.Entity("SistemaPredio.Model.Apartamento", b =>
                {
                    b.HasOne("SistemaPredio.Model.Morador", "Morador")
                        .WithMany()
                        .HasForeignKey("cpfMorador")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Morador");
                });

            modelBuilder.Entity("SistemaPredio.Model.Morador", b =>
                {
                    b.HasOne("SistemaPredio.Model.Usuario", "Usuario")
                        .WithOne()
                        .HasForeignKey("SistemaPredio.Model.Morador", "UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("SistemaPredio.Model.Apartamento", b =>
                {
                    b.Navigation("Alugueis");
                });

            modelBuilder.Entity("SistemaPredio.Model.Morador", b =>
                {
                    b.Navigation("Alugueis");
                });
#pragma warning restore 612, 618
        }
    }
}
